### ISSUE TITLE
Import error with newer itsdangerous versions

### ISSUE THREAD

**Issue by simcop2387** [MycroftAI/selene-backend#283]
**Describe the bug**
Selene does not work with `itsdangerous>2.0.1`

This is characterized by:

```
ImportError: cannot import name 'json' from 'itsdangerous' (/home/mycroft/.local/share/virtualenvs/market-HF8OUXd-/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

**To Reproduce**
Try running/installing with Python 3.9, or otherwise updating the Pipfile.lock for the account and market api services.  Basically any kind of update

**Expected behavior**
No import error related to `json` or `itsdangerous`.

A quick work around is to declare it as an explicit dependency in the Pipfile, instead of relying only on the Pipfile.lock

```
[packages]
flask = "<1.1"
requests = "*"
pyjwt = "*"
uwsgi = "*"
markdown = "*"
selene = {path = "./../../shared"}
itsdangerous = "==2.0.1"
```

**Comment by chrisveilleux** [comment]
Thank you for reporting this issue.  It has been resolved in the dev branch and will be included in the next release.  See PR #308
